/**
 * Todo API
 * Todo List API with NestJS, TypeORM, and PostgreSQL
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TodoList } from './todoList';

export interface Todo {
    id: number;
    title: string;
    description: string;
    completed: boolean;
    dueDate: string;
    order: number;
    todoListId: number;
    todoList: TodoList;
}
