services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - "${PG_ADMIN_PORT}:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: api
    environment:
      - APP_ENV=${APP_ENV}
      - PORT=${API_PORT}
      - OP_SERVICE_ACCOUNT_TOKEN=${OP_SERVICE_ACCOUNT_TOKEN}
    ports:
      - "${API_PORT}:3000"
      - "${API_DEBUG_PORT}:9229"
    depends_on:
      - db
    volumes:
      - ./apps/api/src:/prod/api/src
      - ~/.aws:/root/.aws

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: web
    environment:
      - APP_ENV=${APP_ENV}
    ports:
      - "${WEB_PORT}:4200"
    volumes:
      - ./apps/web/src:/prod/web/src
    depends_on:
      - api

volumes:
  pgdata:
  pgadmin:

