import { HttpEvent, HttpHandlerFn, HttpInterceptorFn, HttpRequest, HttpResponse } from '@angular/common/http';
import { map, Observable } from 'rxjs';

/**
 * Unwraps the standard API response envelope `{ data, meta }`.
 *
 * The NestJS `TransformInterceptor` wraps all successful responses in:
 * ```json
 * { "data": T, "meta": { "timestamp", "correlationId", "path" } }
 * ```
 *
 * This interceptor extracts `data` so that Angular services and
 * components receive the inner payload directly, matching the
 * types generated by the OpenAPI client.
 */
export const apiResponseUnwrapInterceptor: HttpInterceptorFn = (
    req: HttpRequest<unknown>,
    next: HttpHandlerFn,
): Observable<HttpEvent<unknown>> => {
    return next(req).pipe(
        map((event) => {
            if (event instanceof HttpResponse && isWrappedResponse(event.body)) {
                return event.clone({ body: event.body.data });
            }
            return event;
        }),
    );
};

function isWrappedResponse(body: unknown): body is { data: unknown; meta: unknown } {
    return body !== null && typeof body === 'object' && 'data' in body && 'meta' in body;
}
