FROM node:20.12.2-alpine

WORKDIR /app/

COPY --from=1password/op:2 /usr/local/bin/op /usr/local/bin/op

COPY yarn.lock package.json /app/

RUN yarn install

COPY . .

CMD ["yarn", "run", "start:dev"]